# Generated by Django 4.2.4 on 2024-01-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('matric_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('passport', models.BinaryField(blank=True, null=True)),
                ('department', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('cgpa', models.FloatField()),
            ],
        ),
    ]
